### ISSUE TITLE
rdocker doesn't seem to be working on mac OS X yosemite

### ISSUE THREAD

**Issue by joaocc** [dvddarias/rdocker#4]
rdocker uuu@10.10.10.10 -v
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
usage: mkfifo [-m mode] fifoname ...
/usr/local/bin/rdocker: line 120: $PIPE: ambiguous redirect
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
/usr/local/bin/rdocker: line 128: read: 3: invalid file descriptor: Bad file descriptor
/usr/local/bin/rdocker: line 125: 3: Bad file descriptor

**Comment by tim-marwick** [comment]
+1

**Comment by cyberbliss** [comment]
I've raised a PR with a fix to enable the script to also run on a Mac

**Comment by joaocc** [comment]
working perfectly. thx!
