### ISSUE TITLE
RDocker doesn't have option to use private key instead of password

### ISSUE THREAD

**Issue by nedyalkov** [dvddarias/rdocker#5]
My server doesn't support password login so I cannot use rdocker with a password. It doesn't support using a private key, thought.

**Comment by apiad** [comment]
It works perfectly for me with the ssh private key. There is no need to have an option for that, since rdocker internally uses plain ssh commands, hence all authentication is done by ssh.

**Comment by joaocc** [comment]
Hi,
How would you use rdocker with a server that I currently need to connect using some SSH options?
```
ssh -i ~/.ssh/my-ssh-key.id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null uuu@server.somethere.com.com -oPort=222
```
or
```
ssh -i ~/.ssh/my-ssh-key.id_rsa uuu@server.somethere.com.com -oPort=222
```
the simpler ``` rdocker uuu@server.somethere.com.com 222 ``` doesn't work.
Thanks

**Comment by apiad** [comment]
Put the options in a custom host entry in your .ssh/config ?

**Comment by joaocc** [comment]
Works beautifully. For some reason I had the impression it didn't work, but was prob due to the Mac OSX that has also been corrected.

**Comment by apiad** [comment]
Great! Glad to help.

**Comment by electrotumbao** [comment]
But it's not so convenient for one-time connections with another identities...
